version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: streaming_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: streaming_db
      MYSQL_USER: streaming_user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - streaming_network

  mongodb:
    image: mongo:latest
    container_name: streaming_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./db/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - streaming_network

  redis:
    image: redis:6.2
    container_name: streaming_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - streaming_network

  api:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: streaming_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - mysql
      - mongodb
      - redis
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=streaming_user
      - MYSQL_PASSWORD=userpassword
      - MYSQL_DATABASE=streaming_db
      - MONGO_URI=mongodb://root:rootpassword@mongodb:27017/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=your-secret-key-here
    networks:
      - streaming_network

volumes:
  mysql_data:
  mongodb_data:
  redis_data:

networks:
  streaming_network:
    driver: bridge
