global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mysql'
    static_configs:
      - targets: ['localhost:9104']  # MySQL Exporter

  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']  # Redis Exporter

  - job_name: 'mongodb'
    static_configs:
      - targets: ['localhost:9216']  # MongoDB Exporter
